#!/usr/bin/env bash

curl \
-X POST \
-A "Jeremy Bot" \
-d "grant_type=password&username=_jeremy_bot&password=$REDDIT_PASS" \
--user "$REDDIT_CLIENT_ID:$REDDIT_CLIENT_SECRET" \
https://www.reddit.com/api/v1/access_token
