#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
    echo "Useage: $0 <access_token>"
    exit 1
fi

TOKEN="$1"

curl \
-H "Authorization: bearer $TOKEN" \
-A "Jeremy Bot" \
https://oauth.reddit.com/api/v1/me
